### ISSUE TITLE
Cant install role do1jlr.restic

### ISSUE THREAD

**Issue by nuz014** [roles-ansible/ansible_role_restic#125]
I am having trubole installing the role do1jlr.restic becuse it does not exist in galaxy.

**Comment by DO1JLR** [comment]
Yess, sorry. I have to cleanup this mess some day but did not find the time for it.

Since ansible switched to galaxy-ng I was no longer able to publish my roles to the do1jlr namespace and all roles moved automatically to the roles-ansible namespace.

https://galaxy.ansible.com/ui/standalone/roles/roles-ansible/restic/
```
ansible-galaxy role install roles-ansible.restic
```

**Comment by nuz014** [comment]
Okay thanks,
So the right role is then roles-ansible.restic? 
Ansible is now failing on "TASK [roles-ansible.restic : (PREPARE) Ensure restic directories exist]" due to "chgrp failed: failed to look up group mygroup" do you know if this is somting that is missing whit my user or is this a error whit the role?

**Comment by nuz014** [comment]
I figerd out that this is a issue when the user and group name are not the same.
